#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Spirit.Resource", IsApplication=true)]

namespace Spirit
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SatelliteMenu.Resource.Animation.popoutMenuItemAnticipateInterpolator = global::Spirit.Resource.Animation.popoutMenuItemAnticipateInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemClickAnim = global::Spirit.Resource.Animation.popoutMenuItemClickAnim;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemClickInterpolator = global::Spirit.Resource.Animation.popoutMenuItemClickInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemInRotateInterpolator = global::Spirit.Resource.Animation.popoutMenuItemInRotateInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemOutRotateInterpolator = global::Spirit.Resource.Animation.popoutMenuItemOutRotateInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuItemOvershootInterpolator = global::Spirit.Resource.Animation.popoutMenuItemOvershootInterpolator;
			global::SatelliteMenu.Resource.Animation.popoutMenuRotateLeftAnim = global::Spirit.Resource.Animation.popoutMenuRotateLeftAnim;
			global::SatelliteMenu.Resource.Animation.popoutMenuRotateRight = global::Spirit.Resource.Animation.popoutMenuRotateRight;
			global::SatelliteMenu.Resource.Attribute.closeOnClick = global::Spirit.Resource.Attribute.closeOnClick;
			global::SatelliteMenu.Resource.Attribute.itemsAngle = global::Spirit.Resource.Attribute.itemsAngle;
			global::SatelliteMenu.Resource.Attribute.mainImage = global::Spirit.Resource.Attribute.mainImage;
			global::SatelliteMenu.Resource.Attribute.radius = global::Spirit.Resource.Attribute.radius;
			global::SatelliteMenu.Resource.Attribute.speed = global::Spirit.Resource.Attribute.speed;
			global::SatelliteMenu.Resource.Id.popoutMenuItem = global::Spirit.Resource.Id.popoutMenuItem;
			global::SatelliteMenu.Resource.Layout.popoutMenuItem = global::Spirit.Resource.Layout.popoutMenuItem;
			global::SatelliteMenu.Resource.String.empty = global::Spirit.Resource.String.empty;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu = global::Spirit.Resource.Styleable.SatelliteMenu;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_closeOnClick = global::Spirit.Resource.Styleable.SatelliteMenu_closeOnClick;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_itemsAngle = global::Spirit.Resource.Styleable.SatelliteMenu_itemsAngle;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_mainImage = global::Spirit.Resource.Styleable.SatelliteMenu_mainImage;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_radius = global::Spirit.Resource.Styleable.SatelliteMenu_radius;
			global::SatelliteMenu.Resource.Styleable.SatelliteMenu_speed = global::Spirit.Resource.Styleable.SatelliteMenu_speed;
			global::LoginScreen.Resource.Drawable.alert = global::Spirit.Resource.Drawable.alert;
			global::LoginScreen.Resource.Drawable.arrow = global::Spirit.Resource.Drawable.arrow;
			global::LoginScreen.Resource.Drawable.bg_login = global::Spirit.Resource.Drawable.bg_login;
			global::LoginScreen.Resource.Drawable.button_login = global::Spirit.Resource.Drawable.button_login;
			global::LoginScreen.Resource.Drawable.button_login_pressed = global::Spirit.Resource.Drawable.button_login_pressed;
			global::LoginScreen.Resource.Drawable.button_login_selector = global::Spirit.Resource.Drawable.button_login_selector;
			global::LoginScreen.Resource.Drawable.button_register = global::Spirit.Resource.Drawable.button_register;
			global::LoginScreen.Resource.Drawable.button_register_pressed = global::Spirit.Resource.Drawable.button_register_pressed;
			global::LoginScreen.Resource.Drawable.button_register_selector = global::Spirit.Resource.Drawable.button_register_selector;
			global::LoginScreen.Resource.Drawable.button_reset = global::Spirit.Resource.Drawable.button_reset;
			global::LoginScreen.Resource.Drawable.button_reset_pressed = global::Spirit.Resource.Drawable.button_reset_pressed;
			global::LoginScreen.Resource.Drawable.button_reset_selector = global::Spirit.Resource.Drawable.button_reset_selector;
			global::LoginScreen.Resource.Drawable.divider_bottom = global::Spirit.Resource.Drawable.divider_bottom;
			global::LoginScreen.Resource.Drawable.divider_top = global::Spirit.Resource.Drawable.divider_top;
			global::LoginScreen.Resource.Drawable.edittext_bg_selector = global::Spirit.Resource.Drawable.edittext_bg_selector;
			global::LoginScreen.Resource.Drawable.edittext_textcolor_selector = global::Spirit.Resource.Drawable.edittext_textcolor_selector;
			global::LoginScreen.Resource.Drawable.Icon = global::Spirit.Resource.Drawable.Icon;
			global::LoginScreen.Resource.Drawable.image_password = global::Spirit.Resource.Drawable.image_password;
			global::LoginScreen.Resource.Drawable.image_password_active = global::Spirit.Resource.Drawable.image_password_active;
			global::LoginScreen.Resource.Drawable.image_username = global::Spirit.Resource.Drawable.image_username;
			global::LoginScreen.Resource.Drawable.image_username_active = global::Spirit.Resource.Drawable.image_username_active;
			global::LoginScreen.Resource.Drawable.password_right_selector = global::Spirit.Resource.Drawable.password_right_selector;
			global::LoginScreen.Resource.Drawable.textfield = global::Spirit.Resource.Drawable.textfield;
			global::LoginScreen.Resource.Drawable.textfield_active = global::Spirit.Resource.Drawable.textfield_active;
			global::LoginScreen.Resource.Drawable.username_right_selector = global::Spirit.Resource.Drawable.username_right_selector;
			global::LoginScreen.Resource.Id.bottomSpace = global::Spirit.Resource.Id.bottomSpace;
			global::LoginScreen.Resource.Id.confirmPasswordEdit = global::Spirit.Resource.Id.confirmPasswordEdit;
			global::LoginScreen.Resource.Id.emailEdit = global::Spirit.Resource.Id.emailEdit;
			global::LoginScreen.Resource.Id.errorLayout = global::Spirit.Resource.Id.errorLayout;
			global::LoginScreen.Resource.Id.errorMessage = global::Spirit.Resource.Id.errorMessage;
			global::LoginScreen.Resource.Id.fake = global::Spirit.Resource.Id.fake;
			global::LoginScreen.Resource.Id.forgotLayout = global::Spirit.Resource.Id.forgotLayout;
			global::LoginScreen.Resource.Id.forgotText = global::Spirit.Resource.Id.forgotText;
			global::LoginScreen.Resource.Id.loginButton = global::Spirit.Resource.Id.loginButton;
			global::LoginScreen.Resource.Id.loginEdit = global::Spirit.Resource.Id.loginEdit;
			global::LoginScreen.Resource.Id.loginLayout = global::Spirit.Resource.Id.loginLayout;
			global::LoginScreen.Resource.Id.loginText = global::Spirit.Resource.Id.loginText;
			global::LoginScreen.Resource.Id.noAccountImage = global::Spirit.Resource.Id.noAccountImage;
			global::LoginScreen.Resource.Id.noAccountSection = global::Spirit.Resource.Id.noAccountSection;
			global::LoginScreen.Resource.Id.noAccountText = global::Spirit.Resource.Id.noAccountText;
			global::LoginScreen.Resource.Id.passwordEdit = global::Spirit.Resource.Id.passwordEdit;
			global::LoginScreen.Resource.Id.registerButton = global::Spirit.Resource.Id.registerButton;
			global::LoginScreen.Resource.Id.registerText = global::Spirit.Resource.Id.registerText;
			global::LoginScreen.Resource.Id.resetButton = global::Spirit.Resource.Id.resetButton;
			global::LoginScreen.Resource.Id.resetText = global::Spirit.Resource.Id.resetText;
			global::LoginScreen.Resource.Id.rootLayout = global::Spirit.Resource.Id.rootLayout;
			global::LoginScreen.Resource.Id.titleLayout = global::Spirit.Resource.Id.titleLayout;
			global::LoginScreen.Resource.Layout.a_login = global::Spirit.Resource.Layout.a_login;
			global::LoginScreen.Resource.Layout.a_register = global::Spirit.Resource.Layout.a_register;
			global::LoginScreen.Resource.Layout.a_reset = global::Spirit.Resource.Layout.a_reset;
			global::LoginScreen.Resource.Layout.a_validationerror = global::Spirit.Resource.Layout.a_validationerror;
			global::LoginScreen.Resource.String.library_name = global::Spirit.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int popoutMenuItemAnticipateInterpolator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int popoutMenuItemClickAnim = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int popoutMenuItemClickInterpolator = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int popoutMenuItemInRotateInterpolator = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int popoutMenuItemOutRotateInterpolator = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int popoutMenuItemOvershootInterpolator = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int popoutMenuRotateLeftAnim = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int popoutMenuRotateRight = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010015
			public const int closeOnClick = 2130771989;
			
			// aapt resource value: 0x7f01000c
			public const int confirm_logout = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int done_button_background = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int done_button_text = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int extra_fields = 2130771969;
			
			// aapt resource value: 0x7f01000d
			public const int fetch_user_info = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int is_cropped = 2130771985;
			
			// aapt resource value: 0x7f010013
			public const int itemsAngle = 2130771987;
			
			// aapt resource value: 0x7f01000e
			public const int login_text = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int logout_text = 2130771983;
			
			// aapt resource value: 0x7f010016
			public const int mainImage = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int multi_select = 2130771975;
			
			// aapt resource value: 0x7f010010
			public const int preset_size = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int radius = 2130771988;
			
			// aapt resource value: 0x7f010008
			public const int radius_in_meters = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int results_limit = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int search_text = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int show_pictures = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int show_search_box = 2130771979;
			
			// aapt resource value: 0x7f010002
			public const int show_title_bar = 2130771970;
			
			// aapt resource value: 0x7f010012
			public const int speed = 2130771986;
			
			// aapt resource value: 0x7f010005
			public const int title_bar_background = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int title_text = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_blue = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_loginview_text_color = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_picker_search_bar_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_picker_search_bar_text = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_usersettingsfragment_connected_shadow_color = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_usersettingsfragment_connected_text_color = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_usersettingsfragment_not_connected_text_color = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_loginview_compound_drawable_padding = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_loginview_padding_bottom = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_loginview_padding_left = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_loginview_padding_right = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_loginview_padding_top = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_loginview_text_size = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_picker_divider_width = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_picker_place_image_size = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_profilepictureview_preset_size_large = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_profilepictureview_preset_size_normal = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_profilepictureview_preset_size_small = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int com_facebook_tooltip_horizontal_padding = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_usersettingsfragment_profile_picture_height = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_usersettingsfragment_profile_picture_width = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_login = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_login_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_login_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_register = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_register_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_register_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_reset = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_reset_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_reset_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_button_blue = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_button_blue_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_button_blue_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_button_blue_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_button_check = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_button_check_off = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_button_check_on = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_button_grey_focused = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_button_grey_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_button_grey_pressed = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_close = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_inverse_icon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_list_divider = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_list_section_header_background = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_loginbutton_silver = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_logo = 2130837531;
			
			// aapt resource value: 0x7f020041
			public const int com_facebook_picker_default_separator_color = 2130837569;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_picker_item_background = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_picker_list_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_picker_list_longpressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int com_facebook_picker_list_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_facebook_picker_list_selector = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_facebook_picker_list_selector_background_transition = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int com_facebook_picker_list_selector_disabled = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int com_facebook_picker_magnifier = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int com_facebook_picker_top_button = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int com_facebook_place_default_icon = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int com_facebook_profile_default_icon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int com_facebook_profile_picture_blank_portrait = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int com_facebook_profile_picture_blank_square = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int com_facebook_tooltip_black_background = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int com_facebook_tooltip_black_bottomnub = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int com_facebook_tooltip_black_topnub = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int com_facebook_tooltip_black_xout = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int com_facebook_tooltip_blue_background = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int com_facebook_tooltip_blue_bottomnub = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int com_facebook_tooltip_blue_topnub = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int com_facebook_tooltip_blue_xout = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int com_facebook_top_background = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int com_facebook_top_button = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int com_facebook_usersettingsfragment_background_gradient = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int divider_bottom = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int divider_top = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int edittext_bg_selector = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int edittext_textcolor_selector = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Icon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int image_password = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int image_password_active = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int image_username = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int image_username_active = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int password_right_selector = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int textfield = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int textfield_active = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int username_right_selector = 2130837568;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090037
			public const int AddDataButton = 2131296311;
			
			// aapt resource value: 0x7f090039
			public const int GetDataButton = 2131296313;
			
			// aapt resource value: 0x7f09003a
			public const int OpenGalleryButton = 2131296314;
			
			// aapt resource value: 0x7f090036
			public const int SignInButton = 2131296310;
			
			// aapt resource value: 0x7f090035
			public const int SignUpButton = 2131296309;
			
			// aapt resource value: 0x7f090010
			public const int bottomSpace = 2131296272;
			
			// aapt resource value: 0x7f09002b
			public const int com_facebook_body_frame = 2131296299;
			
			// aapt resource value: 0x7f09002d
			public const int com_facebook_button_xout = 2131296301;
			
			// aapt resource value: 0x7f09001b
			public const int com_facebook_login_activity_progress_bar = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int com_facebook_picker_activity_circle = 2131296282;
			
			// aapt resource value: 0x7f09001d
			public const int com_facebook_picker_checkbox = 2131296285;
			
			// aapt resource value: 0x7f090021
			public const int com_facebook_picker_checkbox_stub = 2131296289;
			
			// aapt resource value: 0x7f090025
			public const int com_facebook_picker_divider = 2131296293;
			
			// aapt resource value: 0x7f090024
			public const int com_facebook_picker_done_button = 2131296292;
			
			// aapt resource value: 0x7f09001e
			public const int com_facebook_picker_image = 2131296286;
			
			// aapt resource value: 0x7f090022
			public const int com_facebook_picker_list_section_header = 2131296290;
			
			// aapt resource value: 0x7f090019
			public const int com_facebook_picker_list_view = 2131296281;
			
			// aapt resource value: 0x7f09001f
			public const int com_facebook_picker_profile_pic_stub = 2131296287;
			
			// aapt resource value: 0x7f09001c
			public const int com_facebook_picker_row_activity_circle = 2131296284;
			
			// aapt resource value: 0x7f09002a
			public const int com_facebook_picker_search_text = 2131296298;
			
			// aapt resource value: 0x7f090020
			public const int com_facebook_picker_title = 2131296288;
			
			// aapt resource value: 0x7f090027
			public const int com_facebook_picker_title_bar = 2131296295;
			
			// aapt resource value: 0x7f090026
			public const int com_facebook_picker_title_bar_stub = 2131296294;
			
			// aapt resource value: 0x7f090023
			public const int com_facebook_picker_top_bar = 2131296291;
			
			// aapt resource value: 0x7f090029
			public const int com_facebook_search_bar_view = 2131296297;
			
			// aapt resource value: 0x7f09002f
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131296303;
			
			// aapt resource value: 0x7f09002e
			public const int com_facebook_tooltip_bubble_view_text_body = 2131296302;
			
			// aapt resource value: 0x7f09002c
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131296300;
			
			// aapt resource value: 0x7f090032
			public const int com_facebook_usersettingsfragment_login_button = 2131296306;
			
			// aapt resource value: 0x7f090030
			public const int com_facebook_usersettingsfragment_logo_image = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int com_facebook_usersettingsfragment_profile_name = 2131296305;
			
			// aapt resource value: 0x7f090014
			public const int confirmPasswordEdit = 2131296276;
			
			// aapt resource value: 0x7f09003b
			public const int dataViewtext = 2131296315;
			
			// aapt resource value: 0x7f090033
			public const int editTextEmailId = 2131296307;
			
			// aapt resource value: 0x7f090034
			public const int editTextPasswordBox = 2131296308;
			
			// aapt resource value: 0x7f090013
			public const int emailEdit = 2131296275;
			
			// aapt resource value: 0x7f090017
			public const int errorLayout = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int errorMessage = 2131296280;
			
			// aapt resource value: 0x7f09000b
			public const int fake = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int forgotLayout = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int forgotText = 2131296266;
			
			// aapt resource value: 0x7f09003c
			public const int imageFromCloudview = 2131296316;
			
			// aapt resource value: 0x7f090000
			public const int large = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int loginButton = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int loginEdit = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int loginLayout = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int loginText = 2131296261;
			
			// aapt resource value: 0x7f09000d
			public const int noAccountImage = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int noAccountSection = 2131296268;
			
			// aapt resource value: 0x7f09000e
			public const int noAccountText = 2131296270;
			
			// aapt resource value: 0x7f090001
			public const int normal = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int passwordEdit = 2131296263;
			
			// aapt resource value: 0x7f090028
			public const int picker_subtitle = 2131296296;
			
			// aapt resource value: 0x7f09003d
			public const int popoutMenuItem = 2131296317;
			
			// aapt resource value: 0x7f090038
			public const int progressBar = 2131296312;
			
			// aapt resource value: 0x7f09000f
			public const int registerButton = 2131296271;
			
			// aapt resource value: 0x7f090012
			public const int registerText = 2131296274;
			
			// aapt resource value: 0x7f090016
			public const int resetButton = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int resetText = 2131296277;
			
			// aapt resource value: 0x7f090003
			public const int rootLayout = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int small = 2131296258;
			
			// aapt resource value: 0x7f090011
			public const int titleLayout = 2131296273;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int a_login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int a_register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int a_reset = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int a_validationerror = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int com_facebook_friendpickerfragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int com_facebook_login_activity_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int com_facebook_picker_activity_circle_row = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int com_facebook_picker_checkbox = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int com_facebook_picker_image = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int com_facebook_picker_list_row = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int com_facebook_picker_list_section_header = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int com_facebook_picker_search_box = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int com_facebook_picker_title_bar = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int com_facebook_picker_title_bar_stub = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int com_facebook_placepickerfragment = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int com_facebook_placepickerfragment_list_row = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int com_facebook_search_bar_layout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int com_facebook_tooltip_bubble = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int com_facebook_usersettingsfragment = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Main = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int popoutMenuItem = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07001e
			public const int app_id = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int app_name = 2131165213;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_choose_friends = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_dialogloginactivity_ok_button = 2131165184;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_internet_permission_error_message = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_internet_permission_error_title = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_loading = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int com_facebook_loginview_cancel_action = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int com_facebook_loginview_log_in_button = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int com_facebook_loginview_log_out_action = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_loginview_log_out_button = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_loginview_logged_in_as = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_loginview_logged_in_using_facebook = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int com_facebook_logo_content_description = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_nearby = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_picker_done_button_text = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int com_facebook_placepicker_subtitle_catetory_only_format = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int com_facebook_placepicker_subtitle_format = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int com_facebook_placepicker_subtitle_were_here_only_format = 2131165197;
			
			// aapt resource value: 0x7f070016
			public const int com_facebook_requesterror_password_changed = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int com_facebook_requesterror_permissions = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int com_facebook_requesterror_reconnect = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int com_facebook_requesterror_relogin = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int com_facebook_requesterror_web_login = 2131165204;
			
			// aapt resource value: 0x7f070019
			public const int com_facebook_tooltip_default = 2131165209;
			
			// aapt resource value: 0x7f070008
			public const int com_facebook_usersettingsfragment_log_in_button = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int com_facebook_usersettingsfragment_logged_in = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int com_facebook_usersettingsfragment_not_logged_in = 2131165194;
			
			// aapt resource value: 0x7f07001b
			public const int empty = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int hello = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int library_name = 2131165210;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080004
			public const int Theme_Login = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int Theme_Splash = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int com_facebook_loginview_default_style = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int com_facebook_loginview_silver_style = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int tooltip_bubble_text = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SatelliteMenu = new int[] {
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 3
			public const int SatelliteMenu_closeOnClick = 3;
			
			// aapt resource value: 1
			public const int SatelliteMenu_itemsAngle = 1;
			
			// aapt resource value: 4
			public const int SatelliteMenu_mainImage = 4;
			
			// aapt resource value: 2
			public const int SatelliteMenu_radius = 2;
			
			// aapt resource value: 0
			public const int SatelliteMenu_speed = 0;
			
			public static int[] com_facebook_friend_picker_fragment = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int com_facebook_friend_picker_fragment_multi_select = 0;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_fetch_user_info = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_login_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_logout_text = 3;
			
			public static int[] com_facebook_picker_fragment = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 6
			public const int com_facebook_picker_fragment_done_button_background = 6;
			
			// aapt resource value: 4
			public const int com_facebook_picker_fragment_done_button_text = 4;
			
			// aapt resource value: 1
			public const int com_facebook_picker_fragment_extra_fields = 1;
			
			// aapt resource value: 0
			public const int com_facebook_picker_fragment_show_pictures = 0;
			
			// aapt resource value: 2
			public const int com_facebook_picker_fragment_show_title_bar = 2;
			
			// aapt resource value: 5
			public const int com_facebook_picker_fragment_title_bar_background = 5;
			
			// aapt resource value: 3
			public const int com_facebook_picker_fragment_title_text = 3;
			
			public static int[] com_facebook_place_picker_fragment = new int[] {
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int com_facebook_place_picker_fragment_radius_in_meters = 0;
			
			// aapt resource value: 1
			public const int com_facebook_place_picker_fragment_results_limit = 1;
			
			// aapt resource value: 2
			public const int com_facebook_place_picker_fragment_search_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_place_picker_fragment_show_search_box = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
